server.port=8081


jwt.secret=${JWT_SECRET}
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port=8083
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/